Cars Update Season 2023-2
Re-Volt-America/rva_cars pull request #9
Opened 2023-09-25 01:40 UTC by EstebanMz

### CARS ADDED

**Rookie:**
Creeki Leeki, Toukka 4x4, HSF-1, E-Razr, Funk Flea, Piccino, Ferrada.

**Amateur:**
Six Shooter, X-6 Nitro, AMCO TC, RC Halo, Rad Signal, Dust Shot, Queen Bee, The Rook, Sugar N' Spice.

**Advanced:**
Camelia, XTAR, Glass Cannon, WILL, Metal Masher.

**Semi-Pro:**
Gridlock, Project Octagon, Maxam RS, Roadkill, Otaku-D, Sidepod, Trundle Buster, Toy-World GT, Chilla, Sir Racealot.

**Pro:** 
Tegelhus, Dasher TC, Sin, Polar Star, Ridgeback, Truckenstein, Wattage.

**Super Pro:** 
Revolution 12, Nahesa, Phantera ART, Oblitenitro, Spedion, Phatendo, Vanguard, RVRC, Disruption, Forged Steel, Powerpython, Wyvern.

### CARS UPDATED

El Gekko, Armand, Drome Champ, Saeger, Starmac, Touga, Hyper XL, La Rossa, Identity X, Napalm, El Gekko, King Moloko, Mambra, Patriot, Reddlum, Road Star, Springtrap, Victoria.

### CARS REMOVED

**Rookie:**
Abracadabra, B59, Poison Ivy, Pyramint, Trirraut, Sweet Treats, Manko XS.

**Amateur:**
Bajrick, Clasica, Gator, Wedge CHZ, D-Decker, Devil, Evac, Elegant, Deep Blue.

**Advanced:**
Ember, Pepperbox, Hammerhead, Snakehead, P147 Turbo, Marauder.

**Semi-Pro:**
Acclaim GT, Dual Signal, Yuurei V8, Bushido RS, Jungle Beast, Ruby, Serranillo, Sneaky, NRG, Kappa II.

**Pro:**
Cintach, Stadium Star, Core400, Black Coffee, ZS-9, EXE TC, G3X.

**Super Pro:**
Alterego, Stinger, Pearl, Reiser, Sapphire, Super Phantum, Track Reaper, Nova, Sideswipe, Volken Champion, Devyaty, Dookur Special, Screamer.

2023-09-25 23:12 UTC, Y100XTT requested changes
Phatendo (nrf_phat) was not meant to be included in next season's pack. I suggest replacing it with Raven https://www.revoltworld.net/dl/raven/ instead.

2023-09-25 23:50 UTC, EstebanMz commented
- Phatendo has been replaced in favor of Raven.
- Reverted some files changed. Now the car files we share with I/O are completely identical (excluding some carboxes).

2023-09-25 23:51 UTC, Y100XTT approved these changes

2023-09-25 23:53 UTC, Y100XTT approved these changes

2023-09-25 23:54 UTC, Y100XTT approved these changes

2023-09-27 03:52 UTC, BGMP approved these changes
Thanks @EstebanMz and @Y100XTT . I'll be merging this now!

2023-09-27 03:53 UTC, merged